import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url);
const read=name=>fs.readFileSync(new URL(name,root),'utf8');
const app=read('app.js');const ctx={window:{}};vm.createContext(ctx);
vm.runInContext(read('data.js')+app.slice(0,app.lastIndexOf('boot();')),ctx);
const run=code=>vm.runInContext(code,ctx);
run(`
const check=(value,label)=>{if(!value)throw new Error(label)};
check(M.questions.length===18,'18 questions');check(M.actions.length===26,'26 actions');
check(new Set(M.questions.map(q=>q.id)).size===18,'unique questions');check(new Set(M.actions.map(a=>a.id)).size===26,'unique actions');
for(const x of [...M.questions,...M.actions]){check(x.refs.PK.length>0&&x.refs.IA.length>0,'both sources '+x.id);check(x.refs.PK.every(p=>p>=1&&p<=110),'PK pages');check(x.refs.IA.every(p=>p>=1&&p<=19),'IA pages');check(x.features.every(f=>M.features[f]),'feature '+x.id);check(x.basis.length>0,'source rationale');}
for(const a of M.actions)check(a.questions.every(q=>qById(q)),'action questions '+a.id);
for(const q of M.questions)check(M.actions.some(a=>a.questions.includes(q.id)),'question without action '+q.id);
state=fresh();check(activeQuestions().length===18,'open profile must not hide questions');check(recommendations().every(r=>r.kind==='study'),'unanswered only study');
for(const q of activeQuestions())state.answers[q.id]='no';check(recommendations().length===0,'negative responses yield no actions');check(uncertainties().length===0,'negative responses not incomplete');
state.answers.Q06='possible';check(recommendation(aById('A07')).kind==='act','preventative action');state.answers.Q06='unknown';check(recommendation(aById('A07')).kind==='study','unknown not investment recommendation');
state.answers.Q06='observed';state.impact.Q06='major';state.confidence.Q06='enough';state.effects.Q06=['stop'];state.readiness.Q06='none';check(!uncertainties().some(x=>x.q.id==='Q06'),'complete risk');state.confidence.Q06='check';check(uncertainties().some(x=>x.q.id==='Q06'),'weak knowledge remains visible');
state.status.A07='done';check(recommendation(aById('A07')).kind==='done','completed is follow-up');
state=fresh();state.all=false;state.features=['premises'];check(!activeQuestions().some(q=>q.id==='Q13'),'office not snow');check(!activeQuestions().some(q=>q.id==='Q15'),'office not ecology');check(activeQuestions().some(q=>q.id==='Q16'),'suppliers common to services too');
state.features=['winter'];state.answers.Q13='possible';check(recommendation(aById('A17')),'snow service alternative');check(!recommendation(aById('A18')),'snow does not infer ice');state.features.push('ice');check(recommendation(aById('A18')),'ice separately declared');
state.features=['production','cold'];check(activeQuestions().some(q=>q.id==='Q05'),'manufacturing cooling');check(!activeQuestions().some(q=>q.id==='Q15'),'industry not forestry by default');
state=fresh();state.answers.Q01='observed';state.answers.Q06='possible';state.impact.Q01='minor';state.impact.Q06='major';check(topRisks()[0].id==='Q06','own severity before observation');
state.selected.A07=selectedPlan(aById('A07'));state.selected.A07.task='Oma <tehtävä> & "testi"';state.selected.A07.owner='Nimi';state.company='<script>bad</script>';state.note='Oma huomio';state.revision++;
const report=summaryHTML();check(report.includes('&lt;tehtävä&gt;'),'report escapes text');check(!report.includes('<script>bad'),'no HTML injection');check(report.includes('KIRJAUS TARKISTETTAVA'),'review flag after change');check(report.includes(CREDIT),'funding credit');check(textExport().includes('Oma <tehtävä>'),'full text export edits');
state.answers.Q06='no';check(!recommendation(aById('A07')),'no overrides old choice');check(summaryHTML().includes('SOVELTUVUUS TARKISTETTAVA'),'stale selection flagged');
state.all=false;state.features=[];state.answers.Q13='observed';check(!topRisks().some(q=>q.id==='Q13'),'hidden answers do not influence summary');
`);
assert(app.includes("window.addEventListener('beforeprint',preparePrint)"));
assert(!/fetch\(|XMLHttpRequest|WebSocket|localStorage|sessionStorage|document\.cookie|sendBeacon/.test(app));
const html=read('index.html'),css=read('style.css');
for(const [,path]of html.matchAll(/(?:src|href)="((?:assets\/|style\.|app\.|data\.)[^\"]+)"/g))assert(fs.existsSync(new URL(path,root)),path);
for(const [,path]of css.matchAll(/url\('([^']+)'\)/g))assert(fs.existsSync(new URL(path,root)),path);
assert(html.includes('lang="fi"')&&html.includes('aria-live="polite"'));
const lum=color=>{const [r,g,b]=color.match(/../g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*r+.7152*g+.0722*b;};
const contrast=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);
for(const [a,b]of [['ffffff','e4003a'],['171717','f5f5f5'],['565656','ffffff'],['565656','f5f5f5'],['ad002c','ffffff'],['a4002a','fff0f4'],['5c4300','fff4d5'],['dddddd','171717']])assert(contrast(a,b)>=4.5,'text contrast');
assert(contrast('777777','ffffff')>=3,'control border contrast');
console.log('PASS: 18 questions, 26 actions, all source mappings, conditional branches, uncertainty/negative/complete states, snow vs ice, severity ordering, revised profile, output escaping, text/print exports, local assets and contrast pairs.');
console.log('No browser, screen-reader or visual print audit performed.');
