import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url),read=n=>fs.readFileSync(new URL(n,root),'utf8');
const app=read('app.js'),ctx={window:{},TextEncoder,Uint8Array,DataView,atob};
vm.createContext(ctx);vm.runInContext(read('data.js')+read('export-xlsx.js')+app.slice(0,app.lastIndexOf('boot();')),ctx);
const run=s=>vm.runInContext(s,ctx);
run(`
const check=(v,s)=>{if(!v)throw Error(s)};
state=fresh();for(const q of activeQuestions())state.answers[q.id]='no';
state.answers.Q06='observed';state.readiness.Q06='planned';
check(recommendation(aById('A07')).kind==='review','experienced with plan reviews existing plan');
check(identified().some(q=>q.id==='Q06'),'plan does not erase observed disturbance');
check(!state.status.A07,'plan never marks individual actions done');
state.selected.A07=selectedPlan(aById('A07'));check(state.selected.A07.task.startsWith('Tarkistetaan'),'planned first task');
check(summaryHTML().includes('Suunnitelma on olemassa'),'readiness in print');
check(summaryHTML().includes('SUUNNITELMA TARKISTETTAVA'),'review in print');
check(planTextExport().includes('Suunnitelma on olemassa'),'readiness in action text');
check(textExport().includes('Suunnitelma on olemassa'),'readiness in full text');
state.readiness.Q06='tested';check(recommendation(aById('A07')).kind==='review','tested still review');
state.readiness.Q06='developing';check(recommendation(aById('A07')).kind==='act','unfinished plan still action');
state.readiness.Q06='unknown';check(uncertainties().some(x=>x.reasons.includes('varautuminen avoin')),'unknown readiness remains open');
state.readiness.Q06='planned';state.answers.Q06='unknown';check(recommendation(aById('A07')).kind==='study','old readiness ignored on unknown');
check(!planTextExport().includes('Suunnitelma on olemassa'),'stale readiness not in summary');
check(!textExport().includes('Suunnitelma on olemassa'),'stale readiness not in full export');
state.answers.Q06='observed';state.company='=HYPERLINK("https://example.invalid","test")';state.note='Huomio: ääkköset & <merkit>';state.selected.A07.owner='=1+1';state.selected.A07.date='Ennen talvea';
check(planTextExport().includes('Ennen talvea'),'target date in text');
check(planRows().some(r=>r.cells.includes('=1+1')),'Excel preserves entered text');
check(questionsView().includes('data-readiness="Q06"'),'native labelled preparedness control');
check(profileView().indexOf('id="company"')<profileView().indexOf('<small id="company-hint"'),'name hint below input');
check(planView().includes('data-excel')&&planView().includes('data-plan-text'),'download controls');
`);
// Optional temporary output for independent package/XML validation.
if(process.argv[2])fs.writeFileSync(process.argv[2],run('window.ActionWorkbook.make(planRows())'));
const mockEl={textContent:'',innerHTML:'',value:0},listeners={};
ctx.document={addEventListener:(type,fn)=>listeners[type]=fn,getElementById:()=>mockEl};
ctx.window.addEventListener=()=>{};ctx.location={hash:''};ctx.setTimeout=()=>0;ctx.clearTimeout=()=>{};
run('render=()=>{};boot();');
listeners.change({target:{dataset:{answer:'Q06'},value:'observed'}});
assert(mockEl.innerHTML.includes('readiness-Q06'),'answer change reveals preparedness without losing answer focus');
listeners.change({target:{dataset:{readiness:'Q06'},value:'tested'}});
assert.equal(run('state.readiness.Q06'),'tested');
listeners.change({target:{dataset:{answer:'Q06'},value:'no'}});
assert.equal(mockEl.innerHTML,'','negative hides preparedness');
console.log('PASS: observed + existing/tested/unfinished plan, independent action completion, missing/stale readiness, all three output paths, literal Excel cells, labelled controls and change handlers.');
